language: cpp
compiler:
  - gcc
  - clang
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - bertrand.cachet@gmail.com
  email:
    on_success: change
    on_failure: always
script: 
  - .tests/run-tests.sh

